name: test
on:
  workflow_dispatch:
jobs:
  a:
    name: a
    runs-on: ubuntu-latest
    steps:
      - run: echo "A"
      - id: set
        run: |
          echo "::set-output name=run_job_b::no"
    outputs:
      run_job_b: ${{ steps.set.outputs.run_job_b }}
  b:
    name: b
    runs-on: ubuntu-latest
    needs:
      - a
    if: needs.a.outputs.run_job_b == 'yes'
    steps:
      - run: echo "B"
      - id: set
        run: |
          echo "::set-output name=run_job_c::no"
    outputs:
      run_job_c: ${{ steps.set.outputs.run_job_c }}
  c:
    name: c
    runs-on: ubuntu-latest
    needs:
      - a
      - b
    if: |
      always() &&
      needs.a.result == 'success' &&
      (needs.b.result == 'success' || needs.b.result == 'skipped' || needs.b.outputs.run_job_c == 'yes')
    steps:
      - run: echo "C"
      